examples:
  disable:
    - if: CONFIG_NAME in ["esp-box", "esp-box-lite"]
      reason: Do not build examples for deprecated BSPs
    - if: IDF_VERSION_MAJOR < 5 and CONFIG_NAME in ["esp32_c3_lcdkit", "esp32_s3_lcd_ev_board", "esp32_s3_usb_otg", "m5stack_core_s3", "m5dial"]
      reason: Example depends on BSP, which is supported only for IDF >= 5.0
    - if: IDF_VERSION_MAJOR < 5 and IDF_TARGET in ["esp32c2", "esp32p4", "esp32c5", "esp32c6"]
      reason: Example depends on target, which is supported only for IDF >= 5.0
    - if: IDF_VERSION_MAJOR < 5 and IDF_VERSION_MINOR < 3 and CONFIG_NAME == "esp32_p4_function_ev_board"
      reason: Example depends on BSP, which is supported only for IDF >= 5.3

components/lcd/esp_lcd_gc9503:
  disable:
    - if: IDF_VERSION_MAJOR < 5 or (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0 and ESP_IDF_VERSION_PATCH < 5) or (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 1 and ESP_IDF_VERSION_PATCH == 1)
      reason: Supported from version 5.0.5 and not supported in version 5.1.1

components/lcd/esp_lcd_gc9503/test_apps:
  disable:
    - if: IDF_VERSION_MAJOR < 5 or (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0 and ESP_IDF_VERSION_PATCH < 5) or (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 1 and ESP_IDF_VERSION_PATCH == 1)
      reason: Supported from version 5.0.5 and not supported in version 5.1.1

components/lcd/esp_lcd_ssd1681:
  disable:
    - if: IDF_VERSION_MAJOR < 5
      reason: Component is supported only for IDF >= 5.0

components/esp_lvgl_port/examples/rgb_lcd:
  disable:
    - if: IDF_VERSION_MAJOR < 5
      reason: Example for RGB LCD is supported only for IDF >= 5.0

components/lcd/esp_lcd_ili9881c:
  disable:
    - if: (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR < 3) or IDF_VERSION_MAJOR < 5
      reason: Component is supported only for IDF >= 5.3
    - if: IDF_TARGET not in ["esp32p4"]
      reason: Component is supported only for esp32p4 target

components/lcd/esp_lcd_st7796/test_apps:
  disable:
    - if: IDF_VERSION_MAJOR < 5
      reason: Component is supported only for IDF >= 5.0
