#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := rainmaker-example
PROJECT_VER := 1.0

# Add RainMaker components and other common application components
EXTRA_COMPONENT_DIRS +=  $(IDF_PATH)/../esp-rainmaker/components  $(IDF_PATH)/../esp-rainmaker/examples/common

include $(IDF_PATH)/make/project.mk
