blank_issues_enabled: false
contact_links:
- name: BSP Repository README
url: https://github.com/espressif/esp-bsp/blob/master/README.md
- name: ESP32 Forum
url: www.esp32.com
- name: Development Guide for BSP
url: https://github.com/espressif/esp-bsp/blob/master/docu/BSP_development_guide.md
