# esp_lvgl_port: Build only on related changes and components used in examples
components/esp_lvgl_port:
  depends_filepatterns:
    - "components/esp_lvgl_port/**"
    - "components/lcd_touch/esp_lcd_touch_tt21100/**"
    - "components/lcd_touch/esp_lcd_touch_gt1151/**"

components/esp_lvgl_port/examples:
  depends_filepatterns:
    - "components/esp_lvgl_port/**"
    - "components/lcd/sh1107/**"
  disable:
    - if: IDF_VERSION < "5.2.0"
      reason: Requires I2C Driver-NG which was introduced in v5.2

components/esp_lvgl_port/test_apps/lvgl_port:
  depends_filepatterns:
    - "components/esp_lvgl_port/**"
  disable:
    - if: IDF_VERSION < "5.2.0"
      reason: Requires I2C Driver-NG which was introduced in v5.2

components/esp_lvgl_port/test_apps/simd:
  depends_filepatterns:
    - "components/esp_lvgl_port/**"
  enable:
    - if: IDF_TARGET in ["esp32", "esp32s3"]
      reason: Supports only xtensa targets

components/ds18b20:
  depends_filepatterns:
    - "components/ds18b20/**"
  disable:
    - if: SOC_RMT_SUPPORTED != 1
      reason: Onewire component depends on RMT peripheral

components/icm42670:
  depends_filepatterns:
    - "components/icm42670/**"
  disable:
    - if: IDF_VERSION < "5.2.0"
      reason: Requires I2C Driver-NG which was introduced in v5.2

components/qma6100p:
  depends_filepatterns:
    - "components/qma6100p/**"
  disable:
    - if: IDF_VERSION < "5.2.0"
      reason: Requires I2C Driver-NG which was introduced in v5.2

components/bh1750:
  depends_filepatterns:
    - "components/bh1750/**"
  disable:
    - if: IDF_VERSION < "5.3.0"

components/lcd_touch/esp_lcd_touch_cst816s/test_apps:
  depends_filepatterns:
    - "components/lcd_touch/esp_lcd_touch_cst816s/**"
  disable:
    - if: IDF_VERSION < "5.2.0"
      reason: Requires I2C Driver-NG which was introduced in v5.2
