components/esp_lvgl_port:
  depends_filepatterns:
    - "components/esp_lvgl_port/**"
    - "components/lcd_touch/**"
    - "components/lcd/**"

components/esp_lvgl_port/examples/rgb_lcd:
  depends_filepatterns:
    - "components/esp_lvgl_port/**"
  enable:
    - if: IDF_TARGET in ["esp32s3", "esp32p4"]
      reason: Supports only targets with RGB peripheral

components/esp_lvgl_port/test_apps/simd:
  depends_filepatterns:
    - "components/esp_lvgl_port/**"
  enable:
    - if: IDF_TARGET in ["esp32", "esp32s3"]
      reason: Supports only xtensa targets

components/ds18b20/examples/ds18b20_read:
  depends_filepatterns:
    - "components/ds18b20/**"
  disable:
    - if: CONFIG_NAME == "rmt" and SOC_RMT_SUPPORTED != 1
      reason: RMT backend variant requires SOC RMT support
    - if: CONFIG_NAME == "uart" and SOC_UART_SUPPORTED != 1
      reason: UART backend variant requires SOC UART support

components/qma6100p:
  depends_filepatterns:
    - "components/qma6100p/**"

components/bh1750:
  depends_filepatterns:
    - "components/bh1750/**"
  disable:
    - if: IDF_VERSION < "5.3.0"
