# Examples: Always build all
examples:
  disable:
    - if: CONFIG_NAME in ["esp-box", "esp-box-lite", "esp32_azure_iot_kit"]
      reason: Do not build examples for deprecated BSPs
    - if: (IDF_VERSION < "5.2.0") and CONFIG_NAME in ["esp_bsp_generic", "esp_bsp_devkit", "m5stack_core"]
      reason: Example depends on BSP, which is supported only for IDF >= 5.2
    - if: (IDF_VERSION < "5.3.0") and CONFIG_NAME in ["esp32_p4_function_ev_board", "esp-box-3", "esp32_s3_lcd_ev_board", "m5_atom_s3"]
      reason: Example depends on BSP, which is supported only for IDF >= 5.3
    - if: (IDF_VERSION < "5.4.0") and CONFIG_NAME in ["m5stack_core_s3", "esp32_s2_kaluga_kit", "esp32_s3_korvo_2", "esp32_s3_eye"]
      reason: Example depends on BSP, which is supported only for IDF >= 5.4

examples/generic_button_led:
  disable:
    - if: IDF_VERSION < "5.2.0"
      reason: Requires I2C Driver-NG which was introduced in v5.2
