# Noglib test_app: Build only in CI, where ENV_BUILD_NOGLIB is set
test_apps/noglib:
  disable:
    - if: ENV_BUILD_NOGLIB == 0

# Legacy common components test_app: Build for changes in components which do not have their own test_app or example
test_apps/components:
  depends_filepatterns:
    - "components/bh1750/**"
    - "components/fbm320/**"
    - "components/hts221/**"
    - "components/lcd/esp_lcd_ra8875/**"
    - "components/lcd_touch/**"
    - "components/mag3110/**"
    - "components/mpu6050/**"
