# LCD Touch components: Build only on related changes
components/lcd_touch/esp_lcd_touch_cst816s:
  depends_filepatterns:
    - "components/lcd_touch/esp_lcd_touch/**"
    - "components/lcd_touch/esp_lcd_touch_cst816s/**"

components/lcd_touch/esp_lcd_touch_ft5x06:
  depends_filepatterns:
    - "components/lcd_touch/esp_lcd_touch/**"
    - "components/lcd_touch/esp_lcd_touch_ft5x06/**"

components/lcd_touch/esp_lcd_touch_gt911:
  depends_filepatterns:
    - "components/lcd_touch/esp_lcd_touch/**"
    - "components/lcd_touch/esp_lcd_touch_gt911/**"

components/lcd_touch/esp_lcd_touch_gt1151:
  depends_filepatterns:
    - "components/lcd_touch/esp_lcd_touch/**"
    - "components/lcd_touch/esp_lcd_touch_gt1151/**"

components/lcd_touch/esp_lcd_touch_stmpe610:
  depends_filepatterns:
    - "components/lcd_touch/esp_lcd_touch/**"
    - "components/lcd_touch/esp_lcd_touch_stmpe610/**"

components/lcd_touch/esp_lcd_touch_tt21100:
  depends_filepatterns:
    - "components/lcd_touch/esp_lcd_touch/**"
    - "components/lcd_touch/esp_lcd_touch_tt21100/**"
