/*
 * SPDX-FileCopyrightText: 2022-2024 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_IMAGES_FILES           2
#define MMAP_IMAGES_CHECKSUM        0xC382

enum MMAP_IMAGES_LISTS {
    MMAP_IMAGES_ESP_LOGO_BIN = 0,        /*!< esp_logo.bin */
    MMAP_IMAGES_ESP_TEXT_BIN = 1,        /*!< esp_text.bin */
};
