name: Build ESP-BSP apps

# This job builds all examples and test_applications in this repo
# Applications are selected for build based on changes files and dependecies defined in .build-test-rules.yml

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    strategy:
      matrix:
        include:
          - idf_ver: "latest"
            parallel_count: 5
            parallel_index: 1
          - idf_ver: "latest"
            parallel_count: 5
            parallel_index: 2
          - idf_ver: "latest"
            parallel_count: 5
            parallel_index: 3
          - idf_ver: "latest"
            parallel_count: 5
            parallel_index: 4
          - idf_ver: "latest"
            parallel_count: 5
            parallel_index: 5
          - idf_ver: "release-v5.1"
            parallel_count: 2
            parallel_index: 1
          - idf_ver: "release-v5.1"
            parallel_count: 2
            parallel_index: 2
          - idf_ver: "release-v5.2"
            parallel_count: 2
            parallel_index: 1
          - idf_ver: "release-v5.2"
            parallel_count: 2
            parallel_index: 2
          - idf_ver: "release-v5.3"
            parallel_count: 2
            parallel_index: 1
          - idf_ver: "release-v5.3"
            parallel_count: 2
            parallel_index: 2
    runs-on: ubuntu-latest
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: Build ESP-BSP applications
        shell: bash
        env:
          IDF_EXTRA_ACTIONS_PATH: "${{ github.workspace }}/examples"
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          . ${IDF_PATH}/export.sh
          pip install idf-component-manager==1.* ruamel.yaml idf-build-apps==2.4.3 --upgrade

          echo "Files changed: ${ALL_CHANGED_FILES}"
          idf-build-apps find --modified-files "${ALL_CHANGED_FILES}"
          idf-build-apps build --parallel-count ${{ matrix.parallel_count }} --parallel-index ${{ matrix.parallel_index }} --modified-files "${ALL_CHANGED_FILES}"
