name: Build examples for Launchpad

on:
  push:
      branches:
      - master

jobs:

  build:
    strategy:
      matrix:
        idf_ver: ["v5.4"]
    runs-on: ubuntu-latest
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Upgrade component manager
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          pip install idf-component-manager==2.* --upgrade

      - name: Action for building binaries and config.toml
        env:
          IDF_EXTRA_ACTIONS_PATH: "${{ github.workspace }}/examples"
        uses: espressif/idf-examples-launchpad-ci-action@v1.0.3
        with:
          idf_version: ${{ matrix.idf_ver }}
          config_file: examples/.idf_build_apps.toml

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: built_files
          path: binaries/

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Download built files
        uses: actions/download-artifact@v4
        with:
          name: built_files
          path: binaries/

      - name: Upload built files to gh pages
        uses: actions/upload-pages-artifact@v3
        with:
            name: gh-pages-launchpad
            path: binaries/

