name: "ESP-IDF build examples to github pages (push)"

on:
  push:
      branches:
      - master

jobs:

  build:
    strategy:
      matrix:
        idf_ver: ["v5.3"]
    runs-on: ubuntu-latest
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Upgrade component manager
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          pip install idf-component-manager==1.* --upgrade

      - name: Action for building binaries and config.toml
        uses: espressif/idf-examples-launchpad-ci-action@v1.0.1
        with:
          idf_version: ${{ matrix.idf_ver }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: built_files
          path: binaries/

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Download built files
        uses: actions/download-artifact@v4.1.7
        with:
          name: built_files
          path: binaries/

      - name: Upload built files to gh pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: binaries/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
