name: Build Doxygen documentation

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - master

jobs:
  build-docu:
    name: Build Doxygen documentation
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: mattnotmitt/doxygen-action@v1.9.5
