name: Build examples for Launchpad

# This job:
# - Build all examples for Launchpad
# - Prepare release check table
# - Deploy all to github-pages (config.toml, release_checker.html)

on:
  push:
      branches:
      - master

permissions:
  pages: write
  id-token: write

jobs:

  build-launchpad:
    strategy:
      matrix:
        idf_ver: ["release-v5.5"]
        parallel_index: [1, 2, 3, 4, 5]
    runs-on: ubuntu-latest
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: Build binaries
        env:
          IDF_EXTRA_ACTIONS_PATH: "${{ github.workspace }}/examples"
        uses: espressif/idf-examples-launchpad-ci-action@v2.0.0
        with:
          idf_version: ${{ matrix.idf_ver }}
          parallel_count: 5
          parallel_index: ${{ matrix.parallel_index }}
          generate_config: false
          config_file: examples/.idf_build_apps.toml

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: binaries-${{ matrix.idf_ver }}-${{ matrix.parallel_index }}
          path: binaries/

  release-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0  # all git history

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run release_checker.py
        run: |
          pip install requests pyyaml tabulate wcwidth pytz
          mkdir site
          python .github/ci/release_checker.py > site/release_checker.html

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: release_checker
          path: site/

  deploy:
    needs:
      - build-launchpad
      - release-check

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Download built files
        uses: actions/download-artifact@v8
        with:
          pattern: binaries-*
          path: binaries/
          merge-multiple: true

      - name: Generate config.toml
        uses: espressif/idf-examples-launchpad-ci-action/generate-config@v2.0.0

      - name: Download release checker
        uses: actions/download-artifact@v8
        with:
          name: release_checker
          path: site/

      - name: Prepare combined site
        run: |
          mkdir pages
          cp -r binaries/* pages/
          cp -r site/* pages/

      - name: Upload combined site to GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: pages/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
