name: Release Checker

on:
  push:
      branches:
      - master
  workflow_dispatch:  # can be run manually


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # all git history

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run release_checker.py
        run: |
          pip install requests pyyaml tabulate wcwidth pytz
          mkdir site
          python .github/ci/release_checker.py > site/release_checker.html

      - name: Upload file to gh pages
        uses: actions/upload-pages-artifact@v3
        with:
          name: gh-pages-release-checker
          path: site
